---
- name: Update system packages
  package:
    update_cache: yes

- name: Install common dependencies
  package:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    state: present
