---
- name: Setup Kubernetes Cluster
  hosts: master,worker
  become: yes
  roles:
    - common
    - containerd
    - kubernetes

- name: Setup Kubernetes Cluster (MASTER)
  hosts: master
  become: yes
  roles:
    - master


- name: Setup Kubernetes Cluster (WORKER)
  hosts: worker
  become: yes
  roles:
    - worker

- name: Setup SonarQube Server
  hosts: sonarqube
  become: yes
  roles:
    - sonarqube

