name: Configuring the Infrastructure


on:
  workflow_dispatch:

jobs:
  configure_infrastructure:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./configuring
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Download-artifact
        uses: actions/download-artifact@v4
        with:
          name: Inventory 
          path: ./

      - name: LS folder
        run: ls -lart

      - name: LS folder configuring
        run: ls -lart ./configuring

      - name: cat inventory
        run: cat ./configuring/inventory

        
