name: Configuring the Infrastructure


on:
  workflow_dispatch:

jobs:
  configure_infrastructure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Download-artifact
        uses: actions/download-artifact@v4
        with:
          name: Inventory
          path: ./configuring/inventory

      - name: LS folder
        run: ls -lart

      - name: LS folder configuring
        run: ls -lart ./configuring

      - name: cat inventory
        run: cat ./configuring/inventory

        
