name: Configuring the Infrastructure


on:
  workflow_dispatch:

jobs:
  configure_infrastructure:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./configuring
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          name: Inventory
          workflow: tofu_merge_master.yaml
          search_artifacts: true
          skip_unpack: false
          path: ./configuring


      # - name: ls inventory
      #   run: cat ./inventory

      - name: Run ansible-lint
        uses: ansible/ansible-lint@main

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: main.yml
          directory: ./
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          
