name: Configuring the Infrastructure


on:
  workflow_dispatch:

jobs:
  configure_infrastructure:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./configuring
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          name: Inventory
          workflow: tofu_merge_master.yaml
          search_artifacts: true
          skip_unpack: false
          path: ./configuring


      - name: GitHub secrets
        run: gh --version

      # - name: ls inventory
      #   run: cat ./inventory

      - name: Run ansible-lint
        uses: ansible/ansible-lint@v24.2.0

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: main.yml
          directory: ./
          key: ${{ secrets.SSH_PRIVATE_KEY }}
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          SONAR_JDBC_USERNAME: ${{ secrets.SONAR_JDBC_USERNAME }}
          SONAR_JDBC_PASSWORD: ${{ secrets.SONAR_JDBC_PASSWORD }}
          SONAR_USERNAME: ${{ secrets.SONAR_USERNAME }}
          SONAR_PASSWORD: ${{ secrets.SONAR_PASSWORD }}
          SONAR_NEW_USER_LOGIN: ${{ secrets.SONAR_NEW_USER_LOGIN }}
          SONAR_NEW_USER_NAME: ${{ secrets.SONAR_NEW_USER_NAME }}
          SONAR_NEW_USER_PASSWORD: ${{ secrets.SONAR_NEW_USER_PASSWORD }} 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PROJECT_NAME: ${{ secrets.PROJECT_NAME }}
          PROJECT_KEY: ${{ secrets.PROJECT_KEY }}
