name: Configuring the Infrastructure


on:
  workflow_dispatch:

jobs:
  configure_infrastructure:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./configuring
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          name: Inventory
          workflow: tofu_merge_master.yaml
          path: ./
          search_artifacts: true

      - name: LS folder
        run: ls -lart

      - name: LS folder configuring
        run: ls -lart ./configuring

      - name: cat inventory
        run: cat ./configuring/inventory

        
