name: Deploy Infrastructure

on:
  workflow_dispatch:
  

jobs:
  deploy_infrastructure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Set up OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: 1.6.2

      # - name: OpenTofu fmt
      #   working-directory: ./provisioning
      #   id: fmt
      #   run: tofu fmt -check
      #   continue-on-error: true 

      - name: OpenTofu Init
        working-directory: ./provisioning
        id: init
        run: tofu init
      
      # - name: OpenTofu Validate
      #   working-directory: ./provisioning
      #   id: validate
      #   run: tofu validate -no-color

      - name: OpenTofu Plan
        working-directory: ./provisioning
        id: plan
        run: tofu plan -out=tfplan -var yandex_token=${{ secrets.YANDEX_TOKEN }} -var yandex_cloud_id=${{ secrets.YANDEX_CLOUD_ID }} -var ssh_public_key=${{ secrets.SHH_PUBLIC_KEY }} 
        continue-on-error: true

      - uses: actions/github-script@v6
        if: github.event_name == 'workflow_dispatch'
        env:
          PLAN: "tofu\n${{ steps.plan.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### OpenTofu Format and Style 🖌\`${{ steps.fmt.outcome }}\`
            #### OpenTofu Initialization ⚙️\`${{ steps.init.outcome }}\`
            #### OpenTofu Validation 🤖\`${{ steps.validate.outcome }}\`
            <details><summary>Validation Output</summary>
      
            \`\`\`\n
            ${{ steps.validate.outputs.stdout }}
            \`\`\`
      
            </details>
      
            #### OpenTofu Plan 📖\`${{ steps.plan.outcome }}\`
      
            <details><summary>Show Plan</summary>
      
            \`\`\`\n
            ${process.env.PLAN}
            \`\`\`
      
            </details>
      
            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Workflow: \`${{ github.workflow }}\`*`;
      
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

                
      - name: OpenTofu Apply
        working-directory: ./provisioning
        id: apply
        run: tofu apply -auto-approve \
            -var="yandex_token=${{ secrets.YANDEX_TOKEN }}" \
            -var="yandex_cloud_id=${{ secrets.YANDEX_CLOUD_ID }}" \
            -var="ssh_public_key=${{ secrets.SHH_PUBLIC_KEY }}" 
