name: TEST
on: workflow_dispatch


jobs:
  Jenkins:
    name: Sending to Jenkins
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          name: Inventory
          workflow: tofu_merge_master.yaml
          search_artifacts: true
          skip_unpack: false
          path: ./

      - name: ls inventory
        run: cat ./inventory

      - name: Extract master IP address
        id: extract_master_ip
        run: |
          master_ip=$(awk '/^master.*ansible_host=/ {sub(/.*=/,"",$2); print $2; exit}' inventory)
          echo "master_ip=${master_ip}" >> $GITHUB_OUTPUT

      # - name: Use master IP address in another step
      #   run: |
      #     master_ip="${{ steps.extract_master_ip.outputs.master_ip }}"
      #     echo ${{ steps.extract_master_ip.outputs.master_ip }}
      #     echo ${{ steps.extract_master_ip.outputs }}
      #     echo "Master IP: $master_ip"

      # - name: Send Master IP to Jenkins
      #   env:
      #     JENKINS_URL: ${{ secrets.JENKINS_WEBHOOK_URL }}
      #     SHARED_SECRET: ${{ secrets.JENKINS_WEBHOOK_SECRET }}
      #   run: |
      #     master_ip=$(awk '/^master.*ansible_host=/ {sub(/.*=/,"",$2); print $2; exit}' inventory)
      #     echo ${master_ip}
      #     curl -X POST \
      #       -H "Content-Type: application/json" \
      #       -H "X-GitHub-Event: push" \
      #       -d "{\"master_ip\": \"'"$master_ip"'"\ }" \
      #       -u "jenkins:"'"$SHARED_SECRET"'" \
      #       "http://158.160.145.140:8080/github-webhook/"
  

      - name: Invoke deployment hook
        uses: distributhor/workflow-webhook@v2
        with:
          webhook_url: "http://158.160.145.140:8080/github-webhook/"
          webhook_secret: ${{ secrets.JENKINS_WEBHOOK_SECRET }}
          data: '{ "master_ip": "${{ steps.extract_master_ip.outputs.master_ip }}" }'


      # - name: Generate HMAC signatures
      #   run: |
      #     master_ip=$(awk '/^master.*ansible_host=/ {sub(/.*=/,"",$2); print $2; exit}' inventory)
      #     payload="{\"master_ip\": \"${master_ip}\"}"
      #     signature_sha1=$(echo -n "${payload}" | openssl dgst -sha1 -hmac "${{ secrets.JENKINS_WEBHOOK_SECRET }}" | cut -d ' ' -f 2)
      #     signature_sha256=$(echo -n "${payload}" | openssl dgst -sha256 -hmac "${{ secrets.JENKINS_WEBHOOK_SECRET }}" | cut -d ' ' -f 2)
      #     echo "::set-output name=signature_sha1::$signature_sha1"    
      #     echo "::set-output name=signature_sha256::$signature_sha256"
        
    
      # - name: Trigger Webhook
      #   run: |
      #     curl -X POST \
      #       -H "Content-Type: application/json" \
      #       -H "X-GitHub-Event: push" \
      #       -H "X-Hub-Signature: sha1=${{ steps.generate_signatures.outputs.signature_sha1 }}" \
      #       -H "X-Hub-Signature-256: sha256=${{ steps.generate_signatures.outputs.signature_sha256 }}" \
      #       -d "${payload}" \
      #       "http://158.160.145.140:8080/github-webhook/"
        
